# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_number', models.IntegerField()),
                ('build_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('o', 'SCENARIO OUTLINE'), ('s', 'SCENARIO'), ('b', 'BACKGROUND')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StepDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('keyword', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StepRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.BigIntegerField()),
                ('status', models.CharField(choices=[('p', 'PASSED'), ('f', 'FAILED'), ('m', 'MISSING'), ('s', 'SKIPPED'), ('e', 'PENDING')], max_length=1)),
                ('error_msg', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='scenariorun',
            name='step_runs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cucumber_reports.StepRun'),
        ),
        migrations.AddField(
            model_name='scenariodefinition',
            name='scenario_runs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cucumber_reports.ScenarioRun'),
        ),
        migrations.AddField(
            model_name='scenariodefinition',
            name='step_definitions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cucumber_reports.StepDefinition'),
        ),
        migrations.AddField(
            model_name='feature',
            name='scenario_definitions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cucumber_reports.ScenarioDefinition'),
        ),
        migrations.AddField(
            model_name='buildrun',
            name='features',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cucumber_reports.Feature'),
        ),
    ]
