# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cucumber_reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildrun',
            name='build_at',
            field=models.DateTimeField(default='2017-12-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buildrun',
            name='features',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cucumber_reports.Feature'),
        ),
        migrations.AlterField(
            model_name='steprun',
            name='error_msg',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
